dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - feature/setup
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "9"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo bash tools/setup/install_geth_1_8_17.sh
  - geth version
install:
  - npm install
  - npm install -g mocha
before_script:
  - memcached -p 11212 -d
  - mkdir -p dynamodb
  - wget https://s3.ap-south-1.amazonaws.com/dynamodb-local-mumbai/dynamodb_local_latest.zip -O ./dynamodb/dynamodb_local_latest.zip
  - unzip ./dynamodb/dynamodb_local_latest.zip
  - wget https://s3.amazonaws.com/gethdummy/data.zip -O ./tests/data.zip
  - unzip ./tests/data.zip -d tests/
  - nohup java -Djava.library.path=./dynamodb/DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
  - ps aux | grep 'memcached'
  - ps aux | grep 'dynamo'
  - sleep 30
  - nohup bash tests/data/geth/run-utility.sh &
  - sleep 10
script:
  - bash tests/test.sh
after_script:
  - kill $(ps aux | grep 'geth' | awk '{print $2}')
  - kill $(ps aux | grep 'DynamoDBLocal.jar' | awk '{print $2}')
  - rm -rf dynamodb
